# Generated by Django 5.2.15 on 2026-06-26 23:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paiement_confirme_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email_destinataire', models.CharField(blank=True, default='', max_length=254)),
                ('envoyee_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='api.commande')),
            ],
            options={
                'db_table': 'facture',
                'ordering': ['-created_at'],
            },
        ),
    ]
