# Generated by Django 5.2.15 on 2026-06-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email_client',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
