# Generated by Django 5.2.15 on 2026-06-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurMeteoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('champ', models.CharField(choices=[('temperature', 'Température'), ('nebulosite', 'Nébulosité'), ('precipitation', 'Précipitation')], max_length=20)),
                ('agregation', models.CharField(choices=[('moyenne', 'Moyenne'), ('min', 'Minimum'), ('max', 'Maximum'), ('somme', 'Somme'), ('amplitude', 'Amplitude (max - min)')], max_length=20)),
                ('heure_debut', models.IntegerField(default=0)),
                ('heure_fin', models.IntegerField(default=23)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'indicateur_meteo_config',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DonneeMeteoHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=120)),
                ('horodatage', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('nebulosite', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='meteofrance', max_length=20)),
            ],
            options={
                'db_table': 'donnee_meteo_horaire',
                'ordering': ['horodatage'],
                'unique_together': {('ville', 'horodatage')},
            },
        ),
    ]
