# Generated by Django 5.2.15 on 2026-06-27 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_indicateurmeteoconfig_donneemeteohoraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.CreateModel(
            name='VenteAgregee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantite', models.IntegerField(default=0)),
                ('source', models.CharField(default='commandes', max_length=20)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_agregees', to='api.categorieplat')),
            ],
            options={
                'db_table': 'vente_agregee',
                'ordering': ['date', 'categorie__nom'],
            },
        ),
    ]
