# Generated by Django 5.2.15 on 2026-07-11 23:26

import api.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_article_fournisseur_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='identifiant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='mot_de_passe',
            field=api.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='SelecteursCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_connexion', models.CharField(blank=True, default='', max_length=500)),
                ('xpath_identifiant', models.CharField(blank=True, default='', max_length=500)),
                ('xpath_mot_de_passe', models.CharField(blank=True, default='', max_length=500)),
                ('xpath_valider', models.CharField(blank=True, default='', max_length=500)),
                ('url_produits', models.CharField(blank=True, default='', max_length=500)),
                ('xpath_produit', models.CharField(blank=True, default='', max_length=500)),
                ('champs', models.JSONField(blank=True, default=dict, help_text="XPath relatifs à un produit : {'libelle': './/h3', 'prix_ht': ...}")),
                ('xpath_page_suivante', models.CharField(blank=True, default='', max_length=500)),
                ('decouvert_le', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selecteurs', to='api.fournisseur')),
            ],
            options={
                'db_table': 'selecteurs_catalogue',
            },
        ),
        migrations.CreateModel(
            name='SynchroCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_cours', max_length=20)),
                ('etape', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('pages_scannees', models.IntegerField(default=0)),
                ('appels_mistral', models.IntegerField(default=0)),
                ('articles_crees', models.IntegerField(default=0)),
                ('articles_maj', models.IntegerField(default=0)),
                ('prix_releves', models.IntegerField(default=0)),
                ('journal', models.JSONField(blank=True, default=list)),
                ('demarre_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synchros', to='api.fournisseur')),
            ],
            options={
                'db_table': 'synchro_catalogue',
                'ordering': ['-demarre_le'],
            },
        ),
    ]
