# Generated by Django 5.2.16 on 2026-07-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fournisseur_identifiant_fournisseur_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='rattachement_auto',
            field=models.BooleanField(default=True, help_text="À la fin d'une synchro, Mistral rattache les articles rapportés à un ingrédient existant, ou en crée un. Décochez pour garder la main."),
        ),
        migrations.AddField(
            model_name='synchrocatalogue',
            name='articles_ignores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchrocatalogue',
            name='articles_rattaches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synchrocatalogue',
            name='ingredients_crees',
            field=models.IntegerField(default=0),
        ),
    ]
