# Generated by Django 5.2.16 on 2026-07-12 22:39

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mistral_partage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='code_postal',
            field=models.CharField(blank=True, default='', help_text='Sert au robot quand le site exige de choisir un magasin ou un drive pour afficher ses prix.', max_length=10),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='session_state',
            field=api.fields.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='promptmistral',
            name='usage',
            field=models.CharField(choices=[('evenements', "Événements — calendrier de fréquentation d'une ville"), ('recette', 'Recettes — génération d’une recette originale'), ('robot_obstacles', 'Robot fournisseur — 0. lever les obstacles (cookies, magasin…)'), ('robot_connexion', 'Robot fournisseur — 1. trouver la page de connexion'), ('robot_navigation', 'Robot fournisseur — 2. atteindre la liste des produits'), ('robot_extraction', 'Robot fournisseur — 3. extraire les produits'), ('robot_rapprochement', 'Robot fournisseur — 4. rattacher aux ingrédients')], max_length=40, unique=True),
        ),
    ]
