# Generated by Django 5.2.16 on 2026-07-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fournisseur_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationMeteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=120)),
                ('departement', models.CharField(max_length=5)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('poste_ouvert', models.BooleanField(default=True)),
                ('type_poste', models.IntegerField(blank=True, null=True)),
                ('maj_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'station_meteo',
                'ordering': ['departement', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='donneemeteohoraire',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donneemeteohoraire',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releves', to='api.stationmeteo'),
        ),
    ]
