version: "3.9"

networks:
  sso-net:
    external: true
    name: sso-lab_sso-net
  dev-net:
    external: true
    name: dev-net

services:

  backend:
    build: ./backend
    container_name: restauration-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8088:8000"
    networks:
      - sso-net
      - dev-net
    volumes:
      - ./backend:/app
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/restauration-api/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 8000}}"

  frontend:
    build: ./frontend
    container_name: restauration-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "4206:80"
    networks:
      - sso-net
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/nginx-entrypoint.sh:/docker-entrypoint.d/40-env-config.sh:ro
    labels:
      caddy: "${DOMAIN}"
      caddy.handle_path: "/restauration/*"
      caddy.handle_path.reverse_proxy: "{{upstreams 80}}"
